### ISSUE TITLE
Outdated pythonfile and compatibility issue

### ISSUE THREAD

**Issue by DoctorDemon** [yezhiyi9670/musescore-web-display#1]
Hey there, really love your project, its exactly what I needed!
But i ran into some issues:
- The Python file for generating the required media uses outdated commands which dont work for MuseScore4.
- While trying to fix it using --score-meta the meta data was completely off and couldnt be used with the player.

I would be glad if you could try to fix it,
kind regards,
S.Z.

**Comment by yezhiyi9670** [comment]
Hi, I have just tried to fix it according to your description. It works with my test score on MuseScore 4.4.2.
